Fixing backend job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -372,108 +372,108 @@ jobs:
       - revert-migrations:
           workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
 
-  # smoke-test:
-  #   docker:
-  #     # Lightweight Docker image that works 
-  #     - image: python:3.10-alpine3.16
-  #   steps:
-  #     # Checkout code from git
-  #     - checkout
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           # your code here
-  #           apk add --update --no-cache ansible tar gzip nodejs npm curl aws-cli
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           # your code here
-  #                 BACKEND_IP=$(aws ec2 describe-instances \
-  #                 --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-  #                 --query "Reservations[*].Instances[*].[PublicIpAddress]" \ 
-  #                 --output text)
-  #                 echo "${API_URL}"
-  #                 export API_URL=http://${BACKEND_IP}:3030
-  #     - run:
-  #         name: Backend smoke test.
-  #         command: |
-  #           # your code here
-  #                 BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-  #                 --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-  #                 --query "Reservations[*].Instances[*].[PublicIpAddress]" \
-  #                 --output text)
-  #                 echo ${BACKEND_PUBLIC_IP}
-  #                 export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-  #                 echo ${API_URL}
-  #                 echo "sleeping for 1 minute"
-  #                 sleep 60
-  #                 if curl -v "${API_URL}/api/status" | grep "ok"
-  #                 then
-  #                   exit 0
-  #                 else
-  #                   exit 1
-  #                 fi
+  smoke-test:
+    docker:
+      # Lightweight Docker image that works 
+      - image: python:3.10-alpine3.16
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            apk add --update --no-cache ansible tar gzip nodejs npm curl aws-cli
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+            BACKEND_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query "Reservations[*].Instances[*].[PublicIpAddress]" \ 
+            --output text)
+            echo "${API_URL}"
+            export API_URL=http://${BACKEND_IP}:3030
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query "Reservations[*].Instances[*].[PublicIpAddress]" \
+            --output text)
+            echo ${BACKEND_PUBLIC_IP}
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            echo ${API_URL}
+            echo "sleeping for 1 minute"
+            sleep 60
+            if curl -v "${API_URL}/api/status" | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
             
-  #   - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           # your code here
-  #           FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com
-  #           if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-  #           then
-  #               exit 0
-  #           else
-  #               exit 1
-  #           fi
-  #     # Here's where you will add some code to rollback on failure  
-  #     - destroy-environment:
-  #         workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
-  #     - revert-migrations:
-  #         workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
+    - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+                exit 0
+            else
+                exit 1
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment:
+          workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
           
-    smoke-test:
-      docker:
-        # Docker image that support job tasks
-        - image: python:3.10-alpine3.16 
-      steps:
-        # Checkout code from git
-        - checkout
-        - run:
-            name: Install dependencies
-            command: |
-              apk add --update --no-cache tar gzip
-              apk add --update --no-cache curl aws-cli
-              apk add --update --no-cache nodejs npm
-        - run:
-            name: Backend smoke test
-            command: |
-              BACKEND_PUB_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query "Reservations[*].Instances[*].[PublicIpAddress]" \
-              --output text)
-              export API_URL=http://${BACKEND_PUB_IP}:3030
-              echo "API_URL=${API_URL}"
-              echo "Wait for Server to accept GET connection request:"
-              sleep 60
-              if [[ 'ok' =~ $(curl -s --connect-timeout 5 ${API_URL}/api/status | grep -o ok) ]];then return 0 else return 1;fi
-        - run:
-            name: Frontend smoke test
-            command: |
-              URL=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees
-              echo ${URL}
+    # smoke-test:
+    #   docker:
+    #     # Docker image that support job tasks
+    #     - image: python:3.10-alpine3.16 
+    #   steps:
+    #     # Checkout code from git
+    #     - checkout
+    #     - run:
+    #         name: Install dependencies
+    #         command: |
+    #           apk add --update --no-cache tar gzip
+    #           apk add --update --no-cache curl aws-cli
+    #           apk add --update --no-cache nodejs npm
+    #     - run:
+    #         name: Backend smoke test
+    #         command: |
+    #           BACKEND_PUB_IP=$(aws ec2 describe-instances \
+    #           --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+    #           --query "Reservations[*].Instances[*].[PublicIpAddress]" \
+    #           --output text)
+    #           export API_URL=http://${BACKEND_PUB_IP}:3030
+    #           echo "API_URL=${API_URL}"
+    #           echo "Wait for Server to accept GET connection request:"
+    #           sleep 60
+    #           if [[ 'ok' =~ $(curl -s --connect-timeout 5 ${API_URL}/api/status | grep -o ok) ]];then return 0 else return 1;fi
+    #     - run:
+    #         name: Frontend smoke test
+    #         command: |
+    #           URL=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees
+    #           echo ${URL}
               
-              if curl -s ${URL} | grep "Welcome"
-              then
-                # Change this(from 1) to 0 after the job fails
-                return 0
-              else
-                return 1
-              fi
+    #           if curl -s ${URL} | grep "Welcome"
+    #           then
+    #             # Change this(from 1) to 0 after the job fails
+    #             return 0
+    #           else
+    #             return 1
+    #           fi
               
-        - destroy-environment:
-            workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
-        - revert-migrations:
-            workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
+    #     - destroy-environment:
+    #         workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
+    #     - revert-migrations:
+    #         workflowID: ${CIRCLE_WORKFLOW_ID:0:7}
 
   cloudfront-update:
     docker:
